apiVersion: v1
kind: Pod
metadata:
  name: game-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-c", "env"]
      env:
        - name: GAME_CONFIGURATION
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: game.properties
  restartPolicy: Never
