kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
  labels:
    app: nginx-server
spec:
  containers:
    - name: app
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "256M"
        limits:
          cpu: "200m"
          memory: "512M"
